### ISSUE TITLE
Readonly sessions without PIN fail unconditionally preventing even the key listing

### ISSUE THREAD

**Issue by Jakuje** [latchset/pkcs11-provider#126]
**Describe the bug**
The PKCS#11 modules should be generally usable before login at least for listing of the keys. The NSS is taking this to the extreme, asking pin before any operation, which is OK, according to the standards, but painful for the users [[1](https://bugzilla.redhat.com/show_bug.cgi?id=1892137)][[2](https://bugzilla.redhat.com/show_bug.cgi?id=2016724)].
For this, the profile objects were invented in PKCS#11 3.0, but there are many PKCS#11 modules not supporting this yet a lot of software that is using OpenSSL and will be expecting this behavior [libssh].

**To Reproduce**
1. Remove the pkcs11-module-token-pin directive from `openssl.cnf`
2. Run search for a public key: `pkey -in $PUBURI -pubin -pubout -out ${TSTOUT}.pub`
3. This fails on cryptic message somewhere deep in creating sessions while attempting to login

**Expected behavior**
The applications should be allowed to list public objects without being prompted for a PIN and without requiring the pin in the configuration file.

**Operating environment (please complete the following information):**
 - OS: Fedora
 - Version 36

**Token and application used (please complete the following information):**
 - Device: SoftHSM, NSS Softokn from testsuite
 - PKCS11 Driver version: *
 - Application: libssh, openssl
 - Version any

**Additional context**
The pkcs11 provider should try to list the objects on the card even without login. The `CKF_LOGIN_REQUIRED` flag says only

> True if there are some cryptographic functions that a user MUST be logged in to perform

so this does not mean that the user needs to be logged in to do ANY operation on the module.

An reproduced and ugly solution that solved the issue for me is available in the follwing branch (but it will probably need some more work to work in all corner cases
https://github.com/Jakuje/pkcs11-provider/tree/login (https://github.com/latchset/pkcs11-provider/compare/main...Jakuje:login)

**Comment by simo5** [comment]
I guess one way to deal with this is to always make login optional but make sure to P11PROV_raise() is we fail to login and login was requested.
This way if the operation later fails the error trace in openssl will show that the issue is lack of login.

One question is what to do in case of *failed* login, we need a way to differentiate between missing credentials, and actual wrong pin being used I think.

And we should probably also immediately mark the pin as bad so that we do not attempt multiple logins with a bad pin, as that can lock a card, we should never try more than one login (when the token says the pin is bad) per process.

Of course nothing we can do if someone enters the bad pin and then multiple processes end up trying one after the other and they lock the token that way.

**Comment by simo5** [comment]
I currently get this:
$ openssl pkey -in $PUBURI -pubin -pubout -out  test.pub
Could not read key of Public Key from pkcs11:type=public;id=%26%7d%fe%5a%68%23%37%da%2c%54%ef%3e%3b%3c%ce%93%79%27%c0%eb

While not cryptic it doesn't help either...
