### ISSUE TITLE
Use __attribute__(cleanup(cleanup function)) in the project?

### ISSUE THREAD

**Issue by simo5** [latchset/pkcs11-provider#128]
This is both a RFE issue as well as an open question to other project contributors.

Although this attribute is no in c11 which is our minimum standard, it is supported by gcc and clang, and makes cleanup of variables a lot nicer as it avoids goto statements in most functions.

I'll leave this here for a little while and see if there is feedback.
If I do not get any major push back I might pick it up and implement later.

**Comment by simo5** [comment]
@jakuje @fabled @dengert @holger-dengler any of you have an opinion on this?

**Comment by dengert** [comment]
What about Windows?  The provider should build on any system where OpenSSL
builds.

**Comment by simo5** [comment]
Does it have to build with msvc or is it ok to require gcc or clang on windows?

**Comment by simo5** [comment]
(note that currently there is no windows compatibility in our sources, I do not believe you can build there at this time)

**Comment by dengert** [comment]
I am suggesting that you not use features that are not used in OpenSSL itself. 

 Grep'ing the OpenSSL source I can not find  any  __attribute__(cleanup(...)) 

Google for"  "msvc" __attribute__ cleanup
leads to many results with some saying msvc can use a C++ try attribute in a macro but most sound like they think it will work.

https://stackoverflow.com/questions/1828550/portable-equivalent-to-gccs-attribute-cleanup

OpenSSL does not provide binaries for Windows, so most packages that use OpenSSL get binaries from one of these:
https://wiki.openssl.org/index.php/Binaries

For example: OpenSC https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Windows says get binaries from https://slproweb.com/products/Win32OpenSSL.html

The OpenSC windows builds are done via Appvoyer that creates .msi files that self install. 
(Since building OpenSC on windows is so complicated, if I submit a PR I use the Appvoyer  .msi file to test it. I gave up trying to build in myself.)  

Its your project, do what you want, but I would hope as open source it will  be easy to use on any platform  here OpenSSL is available.

**Comment by fabled** [comment]
I personally prefer Linux kernel style `goto` exit handling. Though, I understand not all like this.

If using attribute cleanup, it probably needs some `#define` things to make it readable, and then it would require careful design on how to do the defines so that defining an auto cleanup variable is not too complicated, and being readable, easily understood without reading the underlying defines. And being greppable.

If Windows is considered to be supported eventually, it makes sense to try to support MSVC.

**Comment by holger-dengler** [comment]
I'm also very familiar with the `goto` exit handling. Anyhow, the cleanup-attribute method is **very** interesting and I would like to get more familiar with it in a project. But if this conflicts with compiling the provider on Windows, I would prefer to stay with a more standard-aligned coding style.

**Comment by Jakuje** [comment]
I have no strong opinions on this. I am well used to the `goto cleanup`-mechanics, but I do not mind learning something new if the portability will not be an issue.

**Comment by simo5** [comment]
goto cleanup is the next best thing when you do not have compiler options to deal with memory, but it still requires paying a lot of attention to all the variables.

The advantage of the cleanup attribute is that you can get al the resources freed automatically when they go out of scope. So you just declare them once and do not have to care too much about getting all the error paths right wrt when to free resources.

I just had to fix an issue caused by mishandling of resources in my latest PR and while there I discovered a change the missed to cleanup a bunch of variables in an early exit due to code being moved around.

I particularly do not want to be tied to MSVC if I do not have to, we already declare C11 to be our base standard and msvc does not officially even support C99, they are stuck at C89.

So the question I guess is:
Is it possible to use appveyor or whatever to build a project on windows but use gcc or clang as modern compilers for C ?

If this is possible the argument is moot and we can sart using attribute(cleanup)

**Comment by dengert** [comment]
I am not a compiler export and have avoided using VS if at all possible. But people are asking for it:
https://developercommunity.visualstudio.com/t/add-support-for-gcc-like-cleanup-attribute-for-pla/1187001

https://learn.microsoft.com/en-us/cpp/overview/install-c17-support?view=msvc-170 says:
"Support for C11 and C17 standards is available in Visual Studio 2019 version 16.8 and later."

https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170

But I can not find if "__attribute__((cleanup))" is standard or optional in C11. 

https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170 implies it can use Clang 8.0.0

**Comment by simo5** [comment]
> But I can not find if "**attribute**((cleanup))" is standard or optional in C11.

It is not a C11 extension, it is an extension implemented by gcc, clang and icc only.
But its usefulness is strong enough I am willing to "limit" the project to those three compilers only.

**Comment by simo5** [comment]
After much consideration, I decided against attribute cleanup for the simple reason that we strive to minimize local allocations anyway in this project. There are some, but the few there are are long lived and cannot be claned-up automatically at the end of the function because they are contextx that are passed back to the caller.
Setting up the whole cleanup macro stuff just for a few cases which still having to handle those other allocations differently feels awkward
