### ISSUE TITLE
Interrupting the FindObjects sequence with other calls as C_GetAttributeValue can lead in incorrect results

### ISSUE THREAD

**Issue by Jakuje** [latchset/pkcs11-provider#148]
The PKCS#11 WG has a page with common bugs and while reading one of the pkcs11 traces from pkcs11-provider, I noticed that it does this: Calling FindObjectsInit, then the GetAttributeValue and then moving on to other objects. 

> C_FindObjectsInit/Find/End can't be interrupted

> Interrupting the sequence C_FindObjectsInit/C_FindObjects/C_FindObjectsEnd with a different call results in inconsistent/erratic results. This makes it difficult to safely perform any general processing of multiple objects rather than just using the find-objects capability as a basic "find me this one object". 

https://wiki.oasis-open.org/pkcs11/CommonBugs

Last time I was writing something like this I think I was pointed to that page by somebody more experienced that this is wrong (even though the wording is not very clear). I changed the code to run the Find, store the handles and then read the objects attributes like this:

https://github.com/OpenSC/OpenSC/blob/master/src/tests/p11test/p11test_case_common.c#L800-L875

I could not find any similar wording in the PKCS#11 specification though and I believe any sane PKCS#11 module should handle this, but if there is somebody with more experience who could add more information, it would be appreciated

**Comment by dengert** [comment]
Are you looking for:
 https://docs.oasis-open.org/pkcs11/pkcs11-base/v3.0/csprd01/pkcs11-base-v3.0-csprd01.html#_Toc10472668
"After calling C_FindObjectsInit, the application may call C_FindObjects one or more times to obtain handles for objects matching the template, and then eventually call C_FindObjectsFinal to finish the active search operation.  At most one search operation may be active at a given time in a given session."

https://docs.oasis-open.org/pkcs11/pkcs11-base/v3.0/csprd01/pkcs11-base-v3.0-csprd01.html#_Toc10472651
"There may be a limit on the number of concurrent sessions an application may have with the token, which may depend on whether the session is “read-only” or “read/write”.  An attempt to open a session which does not succeed because there are too many existing sessions of some type should return CKR_SESSION_COUNT."

OpenSC allows an unlimited number of sessions, and each session can have one of each of theses operations active at a time:
https://github.com/OpenSC/OpenSC/blob/master/src/pkcs11/sc-pkcs11.h#L258-L269
i.e. only one `SC_PKCS11_OPERATION_FIND`

**Comment by simo5** [comment]
@Jakuje perhaps we should make sure a separate session is used, however it seem simply safer to complete the search operation first, and do any parsing later as you propose, so that we limit the need for concurrent sessions, a scarce resource with some tokens.
