### ISSUE TITLE
RFC: Usefulness of debug messages

### ISSUE THREAD

**Issue by Jakuje** [latchset/pkcs11-provider#149]
Currently, the debug messages are very rough and not much verbose. Getting hang of what is going on there is sometimes hard for the people who did not write the code.

From debugging other projects for years, I was very happy with the verbosity of debug messages, that contain at least a function name in them so it is easy to figure out where the message comes from. For example, now messages can look like this:
```
Get session on slot 18
Error: 224
Failed to get session to load keys
```
The way to figure out which error is the above is mostly about grepping for some strings that look like they should be fixed (sometimes already in other function or in other file) and then guessing where the code went through. The least would be the function name, similarly like this which should already give rough estimate where the message comes from (this is something like OpenSSH):
```
p11prov_get_session: Get session on slot 18
p11prov_session_open: Error: 224
store_fetch: Failed to get session to load keys
```

Even better would be to have there exact location in the file, as sometimes functions are not always in the file where I would expect them to be. Adding pid or thread ID might also come very helpful when this will be used in multi-thread/multi-process applications in the future (this is similar what we have in OpenSC now):
```
[1234][T1] session.c:714 p11prov_get_session: Get session on slot 18
[1234][T1] session.c:471 p11prov_session_open: Error: 224
[1234][T1] store.c:106 store_fetch: Failed to get session to load keys
```

Additionally, I found useful in the past log messages at the beginning of any non-trivial function that record the function was called. This makes easy to trace the program and see where it went off the path I would expect.

The last minor note would be interpretation of the CKR values or printing these values in hexadecimal, as that is easier to find in the header files. Having the following log would already give much more information than the decimal number in the previous cases:
```
Error: 0xD0 (TEMPLATE_INCOMPLETE) 
```
This is mostly request for comments if somebody sees some additional information that would be useful to get logged or if you see some drawbacks of logging some of the information before I will start rewriting this code.

**Comment by beldmit** [comment]
Do we need effectively duplicate pkcs11-spy functionality?

**Comment by Jakuje** [comment]
> Do we need effectively duplicate pkcs11-spy functionality?

Its not about duplicating the pkcs11 spy functionality. This is about tracing what is going on in the provider itself and not on the pkcs11 interface only.

**Comment by beldmit** [comment]
Thanks! Yes, it's worth doing and current OpenSSL mechanism can be used, I think. Unfortunately, it lacks the log-level conception :(

**Comment by simo5** [comment]
@Jakuje I intended to add that on the last debug refactoring, then got distracted in the middle of that work.
All debugging is done through a macro today, so it is just a matter of adding that info by using the right stuff in the macros.
I also thought that we should probably simplify how the macro works, I tried to be clever and use synchronization primitives to carefully check for the debug level. But in retrospect debugging is not a big deal, we should probably remove all the (costly) use of synchronization (because that happens even when debugging is not being used) to check if the static debug variable is set and just change the macros to add as much info as possible on the insertion point.
I may take this on actually, thanks for opening the issue.
