### ISSUE TITLE
The `store_fetch()` logic is (still) flawed

### ISSUE THREAD

**Issue by Jakuje** [latchset/pkcs11-provider#212]
**Describe the bug**
Debugging an issue with getting public keys from certificates, I am hitting weird issues with SoftHSM, which I believe are caused by a flawed logic in the `store_fetch()` function.

The `store_fetch()` iterates through all slots, tries to get a session in that slot and then read objects. This works ok for "good" slots, but SoftHSM intentionally provides a "bad" slot, which has `CKF_TOKEN_PRESENT`, but the token does not have `CKF_TOKEN_INITIALIZED` flag, which makes the `check_slot()` function in `p11prov_get_session()` immediately fail with `CKR_TOKEN_NOT_PRESENT`, which is then propagated to the `store_fetch()`, leading to the error `Failed to get session to load keys` and immediate return from the function without checking any further slots. This has the following implications:

 * if the "bad" slot is listed before the "good" slot, the provider will never try to read from the "good" slot
 * it might lead to random failures depending on the slot order
 * The error "Failed to get session to load keys" not being fatal for the store might be confusing when debugging other issues.

**To Reproduce**
1. Run tests with softhsm
2. Observe pkcs11 provider debug logs
3. See the `Failed to get session to load keys` error

**Expected behavior**
The above `error` should probably be only warning or debug message. It should be error only if the only slot that is available fails like this or some similar heuristic. There should be probably better debug messages around the store handling.

**Operating environment (please complete the following information):**
 - OS: Fedora
 - Version 36

**Token and application used (please complete the following information):**
 - Device: SoftHSM

**Comment by dengert** [comment]
> SoftHSM intentionally provides a "bad" slot, which has CKF_TOKEN_PRESENT, but the token does not have CKF_TOKEN_INITIALIZED"

It looks like Softhsm2 will always have a final slot with  CKF_TOKEN_PRESENT and not CKF_TOKEN_INITIALIZED by design. 
the `softhsm2-util` can use the `--free` option to  "Use the first free/uninitialized token." to add another token in a slot.

The wording maybe a little off. Some tests to create 3 tokens then delete the second one created, then listing the slots: 

```
sudo softhsm2-util --init-token --free --label "DEE-1" --serial 0001 --pin 123456 --so-pin 12345678
sudo softhsm2-util --init-token  --free --token "DEE-2" --label "dee-2" --pin 123456 --so-pin 12345678
sudo softhsm2-util --init-token  --free --token "DEE-3" --label "dee-3" --pin 123456 --so-pin 12345678
sudo softhsm2-util --delete-token --token "dee-2"
sudo pkcs11-tool --module /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so -L
Available slots:
Slot 0 (0x266b651b): SoftHSM slot ID 0x266b651b
  token label        : DEE-1
  token manufacturer : SoftHSM project
  token model        : SoftHSM v2
  token flags        : login required, rng, token initialized, PIN initialized, other flags=0x20
  hardware version   : 2.6
  firmware version   : 2.6
  serial num         : 512bf308266b651b
  pin min/max        : 4/255
Slot 1 (0x7ac21790): SoftHSM slot ID 0x7ac21790
  token label        : dee-3
  token manufacturer : SoftHSM project
  token model        : SoftHSM v2
  token flags        : login required, rng, token initialized, PIN initialized, other flags=0x20
  hardware version   : 2.6
  firmware version   : 2.6
  serial num         : 90c5124dfac21790
  pin min/max        : 4/255
Slot 2 (0x2): SoftHSM slot ID 0x2
  token state:   uninitialized
```
shows there is no "free/uninitialized" slot in the middle, only at the end. 

But if while a PKCS11 application has a slot list and it or some other application deleted or remover a token -  the original PKCS11 application's  slot list will remain the same, but if an attempt to access the token the PKCS11 module would return 
an error.   pkcs11-base-v3.0-os says:

 • CKR_DEVICE_ERROR: Some problem has occurred with the token and/or slot. This error code can
 be returned by more than just the functions mentioned above; in particular, it is possible for
 C_GetSlotInfo to return CKR_DEVICE_ERROR. 
  • CKR_TOKEN_NOT_PRESENT: The token was not present in its slot at the time that the function was
 invoked. 
 • CKR_DEVICE_REMOVED: The token was removed from its slot during the execution of the function.
 The relative priorities of these errors are in the order listed above, e.g., if either of
 CKR_DEVICE_MEMORY or CKR_DEVICE_ERROR would be an appropriate error return, then 
 CKR_DEVICE_MEMORY should be returned. 
 In practice, it is often not critical (or possible) for a Cryptoki library to be able to make a distinction
 between a token being removed before a function invocation and a token being removed during a
 function execution.

**Comment by dengert** [comment]
If I use p11-kit and set "priority" for modules to force `softhsm2.so` to be before `opensc-pkcs11.so`  and have a smartcard inserted, I can get:
```
/usr/share/p11-kit/modules$ sudo pkcs11-tool --module /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 -L
Available slots:
Slot 0 (0x11): SoftHSM slot ID 0x266b651b
  token label        : DEE-1
  token manufacturer : SoftHSM project
  token model        : SoftHSM v2
  token flags        : login required, rng, token initialized, PIN initialized, other flags=0x20
  hardware version   : 2.6
  firmware version   : 2.6
  serial num         : 512bf308266b651b
  pin min/max        : 4/255
Slot 1 (0x12): SoftHSM slot ID 0x7ac21790
  token label        : dee-3
  token manufacturer : SoftHSM project
  token model        : SoftHSM v2
  token flags        : login required, rng, token initialized, PIN initialized, other flags=0x20
  hardware version   : 2.6
  firmware version   : 2.6
  serial num         : 90c5124dfac21790
  pin min/max        : 4/255
Slot 2 (0x13): SoftHSM slot ID 0x2
  token state:   uninitialized
Slot 3 (0x14): Identiv SCR3500 A Contact Reader [CCID Interface] (5430214060...
  token label        : Test E. Cardholder V
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 1e649c86501843e2
  pin min/max        : 4/8
```
So something like this could be used to debug the provider.

**Comment by dengert** [comment]
Another possible problem could be in here:
https://github.com/latchset/pkcs11-provider/blob/main/src/session.c#L1112-L1140

line 1122:   `id = CK_UNAVAILABLE_INFORMATION;` 

If  line 1125 `ret = check_slot(slot, uri, mechtype, rw);` or line 1131 `ret = slot_login(slot, uri, pw_cb, pw_cbarg, NULL);` fails 
fail,  line 1117 `if (id != CK_UNAVAILABLE_INFORMATION && id != slot->id) {` will always fail from then on.

I would propose  the `else` clause line 1120 - 1123 should be dropped, so `id` is not reset.

This would also allow for  duplicate `slot->id` values as `check_slot` will also check the URI too.

(Not sure if p11-kit (or any pkcs11 module} would enforce unique `slot->id` values.)

**Comment by simo5** [comment]
@dengert yeah that makes sense

**Comment by Jakuje** [comment]
The solution of changing the `return` to `continue` and changing the raise to debug log sounds good to me. The current behavior lead me into looking into completely wrong place where this error was instead of debugging the real source of the problem.

**Comment by simo5** [comment]
> @dengert yeah that makes sense

Re-reading the code, I think I just need to add some comment to explian what is going on.
Setting id = CK_UNAVAILABLE_INFORMATION is crucial to properly cycle through slots.
It is doen to prevent the other branch to ever fire again.

What is happening here is that the caller is sifting through slots to find a match.
The URI matching may match multiple keys in multiple slots, and downstream there may be additional mathing done that can't be done at the PKCS#11 level.

For example, if you want to list all available public keys the URI can be as simple as pkcs11:type=public

In this case what we want is to skip all slots already returned by *previous* calls.
The caller calls with id = *next_slot (returned by previous call) or CK_UNAVAILABLE_INFORMATION (for the first call).

So that code, if id is set to a valid value, just skips all previously seen slots.
Once it reaches the same point as previously it intentionally resets id, because we want to step through all following slots until we find one that matches. In that case we return it, together with next_slot. On a new cal we resume again seeking to the next_slot, at which point we reset the id so we can cycle again through any following slot.
