### ISSUE TITLE
install pkcs11-provider via homebrew formulae

### ISSUE THREAD

**Issue by avoidik** [latchset/pkcs11-provider#264]
**Describe the feature**

I would like to be able to install pkcs11-provider provider as a homebrew formula on macos

**Expected behavior**

When I run `brew install pkcs11-provider` I should see `pkcs11.dylib` in `/opt/homebrew/lib/ossl-modules/`.

**Additional context**

I wasn't able to achieve that on individual level. Perhaps you'll be more lucky in that. https://github.com/Homebrew/homebrew-core/pull/136249

**Comment by neverpanic** [comment]
I'm not sure that's something we're going to work on upstream.

I'm the only one in the team with a Mac, and I'm both a MacPorts packager, and completely unfamiliar with Homebrew's packaging guidelines. It seems homebrew has inclusion criteria that this project does not yet meet (probably only because it's very new), but there's nothing we can do about this upstream.

**Comment by avoidik** [comment]
Leaving their inclusion criteria alone do you think you would be able to maintain your own Homebrew repository instead of doing it upstream?

**Comment by simo5** [comment]
@avoidik sorry but downstream support (whether it is a linux distribution or some macos distribution) is not a goal for this project.
You are free to open a discussion to seek fello wMac users that want to help you maintain somethin in Homebrew or macports, but as an issue this is invalid.

**Comment by avoidik** [comment]
Of course, thank you. So, if someone out there would want to install it via homebrew on macos here is my personal homebrew formula. Cheers 

https://github.com/avoidik/homebrew-pkcs11-provider
