### ISSUE TITLE
Implement key generation

### ISSUE THREAD

**Issue by fabled** [latchset/pkcs11-provider#34]
The provider-keymgmt API supports key generation. This ticket is feature holder to implement the EC/RSA key generation support.

**Comment by simo5** [comment]
I started looking into this.
I have code that will actually generate an RSA key:
https://github.com/latchset/pkcs11-provider/compare/main...simo5:pkcs11-provider:rsa_keygen

However this is not sufficient as encoders/decoders (at the very least) are needed to deal with "storing" these keys.

Also currently the keys are stored on a session, not written to the token, but there is nothing that guarantees the session is around by the time we get around storing the keys.

I think what is needed first is the session code that uses storage objects so we can refcount sessions and keep them around as busy until all users are done.

The code can be tested with something like:
openssl genpkey -propquery provider=pkcs11 -algorithm PKCS11-RSA -out file.pub

Note that the propquery must be esplicitly set otherwise openssl will of course prefer its own RSA genration code.

**Comment by simo5** [comment]
Fixed in #56
