### ISSUE TITLE
operations_init() called too late? Call it in p11prov_query_operation() ?

### ISSUE THREAD

**Issue by ifranzki** [latchset/pkcs11-provider#370]
We are currently trying to run the `nginx` web server using a HSM based private key via the pkcs11-provider and URI-PEM support. In general this works well, but there are some gotchas:

The `nginx` server does first initialize an SSL context  via `SSL_CTX_new()` and only afterwards it loads the private key PEM file. During `SSL_CTX_new()` OpenSSl fetches a lot of algorithms from the providers. It also calls `p11prov_query_operation()` from the pkcs11-provider for the first time during this. However, at that time the provider context state is still `P11PROV_UNINITIALIZED`, and non of the dynamically loaded algorithms are set up yet.  Unfortunately, OpenSSL remembers that it did query the provider already, and won't query it again at a later time.

During loading of the URI-PEM `p11prov_store_open()` calls `p11prov_ctx_status()` which then initializes the operations. 

However, once it tries to use the private key the first time for a signature operation, it does not find a signature method of the pkcs11-provider, because it uses the information from when it queried it during `SSL_CTX_new()`.

Yes, I know there is `pkcs11-module-load-behavior = early` and with that it does work. 

However, I wonder if it would not make sense to initialize the operations inside `p11prov_query_operation()` if it is called for one of the operations that are loaded dynamically (and it has not yet been initialized)? It does not make any sense to return a NULL algorithm result from `p11prov_query_operation()` if we haven't initialized the operations yet.

What also helps is to set `*no_cache = 1` in `p11prov_query_operation()`. This could for example be done only if the status is still uninitialized, e.g. like this:
`*no_cache = ctx->status == P11PROV_UNINITIALIZED ? 1 : 0;`
That way it will keep querying the provider until the operations got initialized.

**Comment by simo5** [comment]
We can't do what you say in p11prov_query_operation(), becuase it would be the same as `pkcs11-module-load-behavior = early`, which we created exactly because loading early is not ok.

The problem is the OpenSSL immediately queries operations in the provider at startup even though there is no operation the provider needs to perform.

It does this looking for hashes implementations if I recall correctly.

We tried to also set the *no_cache value in early development and got the opposite behavior of what it seems to advertise, with cache set it would permanently cache incorrect information and never ever query again. Unclear if this has changed since early 3.0.2 days.

The problem is that this is a very lightly tested area in openssl and we still need to do some research (and probably open some bugs in openssl) to nail down delayed initialization.

**Comment by ifranzki** [comment]
Yea, initializing the operations in `p11prov_query_operation()` is probably pretty much as early as with `pkcs11-module-load-behavior = early`.

I did test with `*no_cache = ctx->status == P11PROV_UNINITIALIZED ? 1 : 0;` and it did behave correctly. It kept querying the operations as long as the status is uninitialized. Once it was initialized, it did cache the results, and did not query again (for the operation that were queried after initialization).

So I guess this would have the least impact in terms of when initialization happens. It should always be safe to not allow to cache the results. This would just result in more queries, but this is exactly what we want as long as the operations are not initialized.

**Comment by simo5** [comment]
I would love a PR that proposes just that caching change for now, and see if it helps with other bugs like #266

**Comment by ifranzki** [comment]
Please see https://github.com/latchset/pkcs11-provider/pull/372

**Comment by ifranzki** [comment]
Yes this is fixed with https://github.com/latchset/pkcs11-provider/pull/372, please close this issue.
(Sorry, I forgot to add the proper `Closes:` tag to the commit).
